version: '0.1'

services:
  zabbix-database:
    image: mysql:latest
    container_name: zabbix-sql-server
    hostname: zabbix-sql-serveri
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Zoomisdeath@1998

  zabbix-server:
    depends_on:
      - zabbix-database
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    container_name: zabbix-server
    hostname: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-sql-server
      DB_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Zoomisdeath@1998
    restart: unless-stopped

  zabbix-web:
    depends_on:
      - zabbix-database
      - zabbix-server
    container_name: zabbix-web-server
    hostname: zabbix-web-server
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix-sql-server
      DB_SERVER_DBNAME: zabbix
      ZBX_SERVER_HOST: zabbix-server
      MYSQL_USER: root
      MYSQL_PASSWORD: Zoomisdeath@1998
